# Generated by Django 5.2.15 on 2026-09-22 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0123_impersonationlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='guest_view_all_features',
            field=models.BooleanField(default=True),
        ),
    ]
