# Generated by Django 5.2.15 on 2026-09-23 17:03

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0129_gam_issue_slas'),
    ]

    operations = [
        migrations.AddField(
            model_name='approvalrequest',
            name='token_version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='customer',
            name='language',
            field=models.CharField(choices=[('el', 'Ελληνικά'), ('en', 'English')], default='el', max_length=5),
        ),
        migrations.CreateModel(
            name='ApprovalItemDecision',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('response', models.CharField(choices=[('approved', 'Approved'), ('changes', 'Changes requested')], max_length=20)),
                ('note', models.TextField(blank=True)),
                ('decided_at', models.DateTimeField()),
                ('approval', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='decisions', to='db.approvalrequest')),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('issue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gam_approval_decisions', to='db.issue')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Approval Item Decision',
                'verbose_name_plural': 'Approval Item Decisions',
                'db_table': 'gam_approval_item_decisions',
                'unique_together': {('approval', 'issue')},
            },
        ),
    ]
