# Generated by Django 5.2.15 on 2026-09-23 20:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0130_gam_customer_language_batch_approval'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingStatement',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('period', models.DateField(help_text='First day of the billed month')),
                ('lines', models.JSONField(default=list)),
                ('deliverables', models.JSONField(default=list)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('language', models.CharField(default='el', max_length=5)),
                ('pdf_key', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('draft', 'Draft, waiting for review'), ('sent', 'Sent to client')], default='draft', max_length=10)),
                ('token_version', models.PositiveIntegerField(default=1)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('sent_to', models.CharField(blank=True, max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='statements', to='db.customer')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'Billing Statement',
                'verbose_name_plural': 'Billing Statements',
                'db_table': 'gam_billing_statements',
                'ordering': ('-period', 'customer__name'),
                'unique_together': {('customer', 'period')},
            },
        ),
    ]
