# Generated by Django 5.2.15 on 2026-09-24 14:57

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models



# GAM: every workspace starts with its current pipeline as the first template
PIPELINE = [
    ("Νέο αίτημα", "#60646C", "backlog", True),
    ("Προσφορά", "#8B5CF6", "backlog", False),
    ("Εγκρίθηκε", "#3B82F6", "unstarted", False),
    ("Σε εξέλιξη", "#F59E0B", "started", False),
    ("Εσωτερικός έλεγχος", "#EAB308", "started", False),
    ("Έγκριση πελάτη", "#F97316", "started", False),
    ("Διορθώσεις", "#EF4444", "started", False),
    ("Έτοιμο για παράδοση", "#14B8A6", "started", False),
    ("Παραδόθηκε", "#46A758", "completed", False),
    ("Τιμολογήθηκε", "#22C55E", "completed", False),
    ("Ακυρώθηκε", "#9AA4BC", "cancelled", False),
]


def seed_pipeline_template(apps, schema_editor):
    Workspace = apps.get_model("db", "Workspace")
    StateTemplate = apps.get_model("db", "StateTemplate")
    StateTemplateItem = apps.get_model("db", "StateTemplateItem")
    for workspace in Workspace.objects.all():
        template, created = StateTemplate.objects.get_or_create(workspace=workspace, name="GAM pipeline")
        if not created:
            continue
        StateTemplateItem.objects.bulk_create(
            StateTemplateItem(template=template, name=name, color=color, group=group, default=default, sequence=(i + 1) * 5000)
            for i, (name, color, group, default) in enumerate(PIPELINE)
        )

class Migration(migrations.Migration):

    dependencies = [
        ('db', '0134_gam_service_billing_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='StateTemplate',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='state_templates', to='db.workspace')),
            ],
            options={
                'verbose_name': 'State Template',
                'verbose_name_plural': 'State Templates',
                'db_table': 'gam_state_templates',
                'ordering': ('name',),
                'unique_together': {('workspace', 'name')},
            },
        ),
        migrations.CreateModel(
            name='StateTemplateItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Created At')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Last Modified At')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='Deleted At')),
                ('id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('color', models.CharField(default='#60646C', max_length=255)),
                ('group', models.CharField(choices=[('backlog', 'Backlog'), ('unstarted', 'Unstarted'), ('started', 'Started'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='backlog', max_length=20)),
                ('sequence', models.FloatField(default=65535)),
                ('default', models.BooleanField(default=False)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_created_by', to=settings.AUTH_USER_MODEL, verbose_name='Created By')),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='db.statetemplate')),
                ('updated_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(class)s_updated_by', to=settings.AUTH_USER_MODEL, verbose_name='Last Modified By')),
            ],
            options={
                'verbose_name': 'State Template Item',
                'verbose_name_plural': 'State Template Items',
                'db_table': 'gam_state_template_items',
                'ordering': ('sequence', 'created_at'),
            },
        ),
        migrations.RunPython(seed_pipeline_template, migrations.RunPython.noop),
    ]
