# Generated by Django 5.2.15 on 2026-09-24 21:34

from django.db import migrations, models



# GAM: new projects keep starting with the GAM pipeline, now as the default template
def gam_pipeline_is_default(apps, schema_editor):
    apps.get_model("db", "StateTemplate").objects.filter(name="GAM pipeline").update(is_default=True)


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0136_gam_project_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='statetemplate',
            name='is_default',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(gam_pipeline_is_default, migrations.RunPython.noop),
    ]
