# Generated by Django 5.2.15 on 2026-09-24 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('db', '0138_gam_custom_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='portal_version',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
